- name: EnGenius Backup
  gather_facts: no
  hosts: ews850
  vars:
    - configs_dir: configs

  tasks:
  - name: Enter magic key
    ansible.builtin.shell: 1d68d24ea0d9bb6e19949676058f1b93

  - name: login command
    ansible.builtin.shell: login

  - name: Copy config from Wifi AP
    ansible.builtin.fetch:
      src: /tmp/backup.gz
      dest: "{{ configs_dir }}/ews850.gz"
      flat: yes