---

firewalls:  
  hosts:
    pfsense:
      gather_facts: no 
      ansible_host: 192.168.91.1
      ansible_ssh_user: admin
      ansible_connection: paramiko

switches:
  vars:
    gather_facts: no

    ansible_connection: network_cli
    ansible_network_os: community.ciscosmb.ciscosmb
    ansible_ssh_user: admin

  hosts:
    sg300: 
      ansible_host: 192.168.91.2

wifi_aps:
  hosts:
    ews850: 
      ansible_host: 192.168.91.3